import type { Metadata } from "next";
import { Monofett, Exo_2 } from 'next/font/google'
import "./globals.css";

const monofett = Monofett({
  weight: '400',
  variable: "--font-monofett",
  subsets: ["latin"]
});

const exo = Exo_2({
  variable: '--font-exo',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${monofett.variable} ${exo.variable} h-full antialiased`}
    >
      <head></head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
